'use client';

import React from "react";

import { RoomWiseSubmissionProps } from "@/types/room-details.types";
import { FullOffSetFormProps } from "@/types/offset-details.types";
import { OffSetSidebar } from "../OffSet";

// Hooks
import { useRoomSubmissionState } from "@/hooks/ptis/RoomSubmission/useRoomSubmissionState";
import { useRoomActions } from "@/hooks/ptis/RoomSubmission/useRoomActions";
import { useOffsetActions } from "@/hooks/ptis/RoomSubmission/useOffsetActions";
import { useRoomInitialization } from "@/hooks/ptis/RoomSubmission/useRoomInitialization";

// Components
import { RoomSubmissionHeader } from "./components/RoomSubmissionHeader";
import { RoomSubmissionFooter } from "./components/RoomSubmissionFooter";
import { RoomSubmissionLayout } from "./components/RoomSubmissionLayout";
import { InlineError } from "./components/InlineError";

// Utils
import { calculateRoomArea, calculateRoomTotal, getDimensionsString, isOffsetValid } from "@/lib/utils/RoomSubmission/room-submission.utils";
import { isRoomComplete } from "@/lib/utils/RoomSubmission/room-validation.utils";
import { focusFieldOrFallback } from "@/lib/utils/floorSubmission/focus-helpers";
import { checkIsUtilityCategory } from "@/lib/utils/floorSubmission/floor-utility-checks";

export const RoomWiseSubmission: React.FC<RoomWiseSubmissionProps & {
  externalAreaUnit?: "sq.m" | "sq.ft";
  onExternalToggleUnit?: () => void;
}> = (props) => {
  const { isOpen, onClose, displayMode = 'modal' } = props;

  const isUtilityCategory = checkIsUtilityCategory(props.floorData?.typeOfUseCategoryId) || 
    props.floorData?.isOpenPlot === true || 
    props.floorData?.selectedFloorType === 'OpenPlot' ||
    String(props.floorData?.conTyp || '').toLowerCase().includes('open plot') ||
    String(props.floorData?.constructionType || '').toLowerCase().includes('open plot') ||
    String(props.floorData?.floor || '').toLowerCase().includes('open plot') ||
    String(props.floorData?.floorDescription || '').toLowerCase().includes('open plot');

  let lastFilledRoomIndex = -1;
  if (Array.isArray(props.existingRooms)) {
    for (let i = props.existingRooms.length - 1; i >= 0; i--) {
      const r = props.existingRooms[i];
      const hasArea = Number(r.area || r.areaSqMtr || r.totalAreaSqMtr || r.total || r.carpetArea || 0) > 0;
      const hasUseOrShape = (r.utilities && r.utilities !== "-Select-") || (r.shape && r.shape !== "-Select-");
      if (hasArea || hasUseOrShape) {
        lastFilledRoomIndex = i;
        break;
      }
    }
  }
  const requiredRoomsCount = lastFilledRoomIndex !== -1 ? lastFilledRoomIndex + 1 : 0;
  const computedMaxRooms = isUtilityCategory ? (props.existingRooms?.length || 0) : Math.max(props.maxRooms || 0, requiredRoomsCount);
  const state = useRoomSubmissionState(isUtilityCategory ? undefined : computedMaxRooms, props.externalAreaUnit);
  const roomActions = useRoomActions(state, props);
  const offsetActions = useOffsetActions(state, roomActions.handleEdit);

  // Initialization & Side Effects
  useRoomInitialization(state, props, roomActions);

  React.useEffect(() => {
    if (isOpen) {
      const timer = setTimeout(() => {
        if (document.querySelector('.z-\\[9999\\]')) return;
        focusFieldOrFallback('room-no-input', 'form');
      }, 150);
      return () => clearTimeout(timer);
    }
  }, [isOpen]);

  // --- Actions ---
  const handleToggleUnit = () => {
    if (props.onExternalToggleUnit) {
      props.onExternalToggleUnit();
    } else {
      state.setInternalAreaUnit(prev => prev === "sq.m" ? "sq.ft" : "sq.m");
    }
  };

  const addNewRow = () => {
    state.setRooms(prev => {
      const updated = [...prev, {
        tempId: `temp-${Date.now()}-${prev.length}`,
        roomNo: (prev.length + 1).toString(),
        length: "0", width: "0", area: 0, roomCount: "1", offsetMinus: "No", outer: "No", total: 0,
        remark: "-Select-", utilities: "-Select-", shape: "-Select-", offsets: [],
        isAutoGenerated: true, shapeParams: { length: "", width: "", radius: "", base: "", height: "", side: "", base1: "", base2: "" }
      }];
      return updated.map((r, i) => ({ ...r, roomNo: (i + 1).toString() }));
    });
  };

  const handleClose = () => {
    state.setValidationErrors({});
    state.setRooms([]);
    state.setEditingIndex(null);
    state.setIsEditMode(false);
    state.setOffsetModalOpen(false);
    onClose();
  };

  const fullOffSetProps: FullOffSetFormProps = {
    offsetModalOpen: state.offsetModalOpen,
    formData: state.formData,
    calculateAdjustedRoomTotal: offsetActions.calculateAdjustedRoomTotal,
    handleSubtractClick: offsetActions.handleSubtractClick,
    selectedOperation: state.selectedOperation,
    isShakingSubtract: state.isShakingSubtract,
    offsetData: state.offsetData,
    setOffsetValidationError: state.setOffsetValidationError,
    setSelectedOperation: state.setSelectedOperation,
    offsetValidationError: state.offsetValidationError,
    selectedShape: state.selectedShape,
    handleShapeChange: offsetActions.handleShapeChange,
    handleOffsetInputChange: offsetActions.handleOffsetInputChange,
    offsetList: state.offsetList,
    getDimensionsString,
    handleDeleteOffset: offsetActions.handleDeleteOffset,
    handleAddOffset: offsetActions.handleAddOffset,
    isOffsetDataValid: () => isOffsetValid(state.offsetData, state.selectedShape),
    handleOffsetOk: offsetActions.handleOffsetOk,
    handleOffsetClose: offsetActions.handleOffsetClose,
    areaUnit: state.areaUnit,
    shouldShake: state.shouldShake,
    deletingOffsetIndex: state.deletingOffsetIndex,
  };

  if (!state.mounted || !isOpen) return null;

  const content = (
    <div className={`w-full p-0 flex flex-col bg-white overflow-visible ${displayMode === 'modal' ? '' : 'mb-6'}`}>
      <form onSubmit={(e) => e.preventDefault()}>
        <div className="bg-white flex flex-col rounded-lg shadow-md border border-gray-200 overflow-visible">

          <RoomSubmissionHeader
            floorNumber={props.floorNumber}
            areaUnit={state.areaUnit}
            handleToggleUnit={handleToggleUnit}
            maxRooms={computedMaxRooms}
            availableRooms={state.availableRooms}
            displayMode={displayMode}
          />

          <RoomSubmissionLayout
            displayMode={displayMode}
            state={state}
            actions={{ addNewRow }}
            roomActions={roomActions}
            offsetActions={offsetActions}
            props={props}
            InlineError={InlineError}
            calculateArea={() => calculateRoomArea(state.formData, state.shapeParameters)}
            calculateTotal={calculateRoomTotal}
            isUtilityCategory={isUtilityCategory}
          />

          <RoomSubmissionFooter
            onSave={roomActions.handleUpdate}
            onClose={handleClose}
            isSaving={state.isUpdating}
            canSave={state.grandTotal > 0 && state.rooms.length > 0 && state.rooms.every(isRoomComplete)}
          />

        </div>
      </form>
      <OffSetSidebar {...fullOffSetProps} />
    </div>
  );

  return content;
};

export default RoomWiseSubmission;
