import { PagedResponse } from "../common.types";
import type React from 'react';
import type { MasterDataGroup, MasterDataRecord } from "./master-data.types";

/** 
 * Form model for creating and editing asset types
 */
export interface AssetTypeFormModel {
  id?: string;
  code: string;
  name: string;
  group: string;
  allowUnitRegistration: boolean;
  allowRoomRegistration: boolean;
  description: string;
  isActive: boolean;
}

/**
 * Interface for the Asset Type record as returned by the backend API.
 */
export interface AssetTypeApiRecord {
  /** Unique numeric identifier generated by the backend */
  id: number;
  /** Human-readable name for the type */
  typeName: string;
  /** Alphanumeric code identifier */
  typeCode: string;
  /** Reference ID to the parent Asset Category */
  categoryId: number;
  categoryName?: string;
  description: string;
  /** Determines if the type is currently available for selection */
  isActive: boolean;
  createdDate?: string;
  updatedDate?: string | null;
  /** Code format requirement enforced by the backend API validation rules */
  codeFormat?: string;
  allowUnitRegistration?: boolean;
  allowRoomRegistration?: boolean;
}

/**
 * Normalized model for Asset Type
 */
export interface AssetType {
  id: number;
  typeCode: string;
  typeName: string;
  categoryId: number;
  categoryName: string;
  description: string;
  isActive: boolean;
  allowUnitRegistration: boolean;
  allowRoomRegistration: boolean;
  createdDate: string;
  updatedDate: string | null;
}

/**
 * Props for Asset Type list component
 */
export interface AssetTypeProps extends Omit<PagedResponse<AssetType>, 'items' | 'hasPrevious' | 'hasNext'> {
  data: AssetType[];
}

/**
 * Parameters for fetching asset types
 */
export interface AssetTypeParams {
  PageNumber?: number;
  PageSize?: number;
  SearchTerm?: string;
  CategoryId?: number;
  SortBy?: string;
  SortOrder?: 'asc' | 'desc';
  IsActive?: string;
}

export interface AssetTypeFormProps {
  initialData: AssetTypeFormModel | null;
  groups: MasterDataGroup[];
}

export interface AssetTypeMasterProps {
  data: MasterDataRecord[];
  pageNumber: number;
  pageSize: number;
  totalCount: number;
  totalPages: number;
  search?: string;
}

export interface FormFieldsSectionProps {
  formData: AssetTypeFormModel;
  errors: Record<string, string>;
  showError: (field: string) => boolean;
  onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => void;
  onBlur: (e: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>) => void;
  onSelectChange: (name: string, value: string) => void;
  onRadioChange: (value: string) => void;
  t: (key: string) => string;
  categoryOptions: { label: string; value: string }[];
}

export interface MandatoryFieldsNoticeProps {
  message: string;
}

export interface StatusToggleCardProps {
  isActive: boolean;
  onToggle: () => void;
  activeLabel: string;
  inactiveLabel: string;
  statusLabel: string;
}

export interface AssetTypeMasterErrorContextType {
  hasError: boolean;
  setHasError: (value: boolean) => void;
}

export interface AssetTypeMasterLayoutContentProps {
  children: React.ReactNode;
}
