import { PagedResponse } from "../common.types";
import type React from 'react';

/** 
 * Form model for creating and editing asset categories
 */
export interface AssetCategoryFormModel {
  id?: string;
  code: string;
  name: string;
  description: string;
  isMovable: boolean;
  hasFloorDetails: boolean;
  hasInventory: boolean;
  isInventoryMandatory: boolean;
  hasLegalCompliance: boolean;
  valuationType: string;
  isActive: boolean;
}

/**
 * Interface for the Asset Category record as returned by the backend API.
 */
export interface AssetCategoryApiRecord {
  /** Unique numeric identifier generated by the backend */
  id: number;
  /** Human-readable name for the category */
  categoryName: string;
  /** Alphanumeric code identifier */
  categoryCode: string;
  description: string;
  /** Determines if the category is currently available for selection */
  isActive: boolean;
  isMovable: boolean;
  hasFloorDetails: boolean;
  hasInventory: boolean;
  /** If hasInventory is true, this determines if it's strictly mandatory */
  isInventoryMandatory: boolean;
  hasLegalCompliance: boolean;
  valuationType: string;
  createdDate?: string;
  updatedDate?: string | null;
  /** True if the record is marked for soft deletion */
  markedForDeletion?: boolean | number;
  /** Code format requirement enforced by the backend API validation rules */
  codeFormat?: string;
}

/**
 * Normalized model for Asset Category
 */
export interface AssetCategory {
  id: number;
  categoryCode: string;
  categoryName: string;
  description: string;
  isActive: boolean;
  isMovable: boolean;
  hasFloorDetails: boolean;
  hasInventory: boolean;
  isInventoryMandatory: boolean;
  hasLegalCompliance: boolean;
  valuationType: string;
  createdDate: string;
  updatedDate: string | null;
}

/**
 * Props for Asset Category list component
 */
export interface AssetCategoryProps extends Omit<PagedResponse<AssetCategory>, 'items' | 'hasPrevious' | 'hasNext'> {
  data: AssetCategory[];
}

/**
 * Parameters for fetching asset categories
 */
export interface AssetCategoryParams {
  PageNumber?: number;
  PageSize?: number;
  SearchTerm?: string;
  IsActive?: string;
  SortBy?: string;
  SortOrder?: 'asc' | 'desc';
}

export interface FormFieldsSectionProps {
  formData: AssetCategoryFormModel;
  errors: Record<string, string>;
  showError: (field: keyof AssetCategoryFormModel) => boolean;
  onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => void;
  onBlur: (e: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>) => void;
  onCheckboxChange: (name: string, checked: boolean) => void;
  t: (key: string) => string;
  isPending?: boolean;
}

export interface AssetCategoryMasterErrorContextType {
  hasError: boolean;
  setError: (error: boolean) => void;
  resetError: () => void;
}

export interface AssetCategoryFormProps {
  initialData: AssetCategoryFormModel | null;
}

export interface AssetCategoryMasterProps {
  data: AssetCategory[];
  pageNumber: number;
  pageSize: number;
  totalCount: number;
  totalPages: number;
  search?: string;
}

export interface AssetCategoryMasterLayoutContentProps {
  children: React.ReactNode;
}

export interface StatusToggleCardProps {
  isActive: boolean;
  onToggle: () => void;
  error?: string;
  activeLabel: string;
  inactiveLabel: string;
  statusLabel: string;
  description?: string;
}

export interface MandatoryFieldsNoticeProps {
  message: React.ReactNode;
}

export type AssetCategoryTableRow = AssetCategory & Record<string, unknown>;
