'use client';

import React from 'react';
import { RuleScope } from '@/types/rule-engine.types';
import { Input, SearchSelect } from '@/components/common';
import { useTranslations } from 'next-intl';


interface TargetFilterPanelProps {
  ruleName: string;
  setRuleName: (val: string) => void;
  description: string;
  setDescription: (val: string) => void;
  priority: number | '';
  setPriority: (val: number | '') => void;
  ruleScopeId: number;
  setRuleScopeId: (val: number) => void;
  ruleCategory: string;
  setRuleCategory: (val: string) => void;
  scopes: RuleScope[];
  corporations: { label: string; value: string }[];
  /** API-driven rule category options from PTIS.RuleCategoryMaster */
  ruleCategoryOptions: { label: string; value: string }[];
}

export default function TargetFilterPanel({
  ruleName, setRuleName,
  ruleScopeId, setRuleScopeId,
  ruleCategory, setRuleCategory,
  description, setDescription,
  priority, setPriority,
  scopes, corporations,
  ruleCategoryOptions,
}: TargetFilterPanelProps) {
  const t = useTranslations('ruleEngine');
  const scopeOptions  = scopes.map((s) => ({ label: s.scopeName, value: s.id.toString() }));
  const displayedCorp = corporations[0]?.label ?? '';

  // Synchronize underlying state if ruleCategory is stale/absent in dynamic options
  React.useEffect(() => {
    const firstOption = ruleCategoryOptions[0]?.value ?? '';
    if (firstOption && !ruleCategoryOptions.some((o) => o.value === ruleCategory)) {
      setRuleCategory(firstOption);
    }
  }, [ruleCategoryOptions, ruleCategory, setRuleCategory]);

  // Ensure the current ruleCategory value exists in the options; default to first item
  const safeCategory =
    ruleCategoryOptions.some((o) => o.value === ruleCategory)
      ? ruleCategory
      : (ruleCategoryOptions[0]?.value ?? '');

  return (
    <div className="flex flex-col gap-5 w-full bg-white p-4 border border-blue-200 rounded-xl shadow-sm">
      <div className="grid grid-cols-1 md:grid-cols-6 gap-4 items-end">

        {/* Rule ID — auto-generated by backend */}
        <div>
          <Input label={t('targetFilter.ruleId')} value={t('targetFilter.ruleIdValue')} disabled className="bg-zinc-50 font-semibold" />
        </div>

        {/* Rule Category — API-driven select */}
        <div>
          <SearchSelect
            label={t('targetFilter.category')}
            options={ruleCategoryOptions}
            value={safeCategory}
            onChange={(_, val) => setRuleCategory(val)}
            required
          />
        </div>

        {/* Rule Name */}
        <div>
          <Input
            label={t('targetFilter.ruleName')}
            value={ruleName}
            onChange={(e) => setRuleName(e.target.value)}
            placeholder={t('targetFilter.ruleNamePlaceholder')}
            required
          />
        </div>

        {/* Rule Scope — from API */}
        <div>
          <SearchSelect
            label={t('targetFilter.ruleScope')}
            options={scopeOptions}
            value={ruleScopeId.toString()}
            onChange={(_, val) => setRuleScopeId(Number(val))}
            required
          />
        </div>

        {/* Corp — read-only from auth context */}
        <div>
          <Input label={t('targetFilter.corp')} value={displayedCorp} readOnly className="bg-zinc-50 font-bold" />
        </div>

        {/* Priority */}
        <div>
          <Input
            label={t('targetFilter.priority')}
            type="number"
            value={priority}
            onChange={(e) => {
              const val = e.target.value;
              setPriority(val === '' ? '' : Number(val));
            }}
            placeholder={t('targetFilter.priorityPlaceholder')}
            min={1}
            required
            fullWidth
          />
        </div>
      </div>

      <div>
        <Input
          label={t('targetFilter.description')}
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder={t('targetFilter.descriptionPlaceholder')}
          fullWidth
        />
      </div>
    </div>
  );
}

