'use client';

import React from 'react';
import { RuleScope } from '@/types/rule-engine.types';
import { Input, SearchSelect } from '@/components/common';
import { useTranslations } from 'next-intl';


interface TargetFilterPanelProps {
  ruleName: string;
  setRuleName: (val: string) => void;
  ruleScopeId: number;
  setRuleScopeId: (val: number) => void;
  ruleCategory: string;
  setRuleCategory: (val: string) => void;
  ruleDescription: string;
  setRuleDescription: (val: string) => void;
  scopes: RuleScope[];
  /** API-driven rule category options from PTIS.RuleCategoryMaster */
  ruleCategoryOptions: { label: string; value: string }[];
}

export default function TargetFilterPanel({
  ruleName, setRuleName,
  ruleScopeId, setRuleScopeId,
  ruleCategory, setRuleCategory,
  ruleDescription, setRuleDescription,
  scopes,
  ruleCategoryOptions,
}: TargetFilterPanelProps) {
  const t = useTranslations('ruleEngine');
  const scopeOptions  = scopes.map((s) => ({ label: s.scopeName, value: s.id.toString() }));
  const safeScope = scopeOptions.some((o) => o.value === ruleScopeId.toString())
    ? ruleScopeId.toString()
    : '';

  // Synchronize underlying state if ruleCategory is stale/absent in dynamic options
  React.useEffect(() => {
    const firstOption = ruleCategoryOptions[0]?.value ?? '';
    if (firstOption && !ruleCategoryOptions.some((o) => o.value === ruleCategory)) {
      setRuleCategory(firstOption);
    }
  }, [ruleCategoryOptions, ruleCategory, setRuleCategory]);

  // Ensure the current ruleCategory value exists in the options; default to first item
  const safeCategory =
    ruleCategoryOptions.some((o) => o.value === ruleCategory)
      ? ruleCategory
      : (ruleCategoryOptions[0]?.value ?? '');

  return (
    <div className="flex flex-col gap-5 w-full bg-white p-4 border border-blue-200 rounded-xl shadow-sm">
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">

        {/* Rule ID — auto-generated by backend */}
        <div>
          <Input label={t('targetFilter.ruleId')} value={t('targetFilter.ruleIdValue')} disabled className="bg-zinc-50 font-semibold" />
        </div>

        {/* Rule Category — API-driven select */}
        <div>
          <SearchSelect
            label={t('targetFilter.category')}
            options={ruleCategoryOptions}
            value={safeCategory}
            onChange={(_, val) => setRuleCategory(val)}
            required
          />
        </div>

        {/* Rule Name */}
        <div>
          <Input
            label={t('targetFilter.ruleName')}
            value={ruleName}
            onChange={(e) => setRuleName(e.target.value)}
            placeholder={t('targetFilter.ruleNamePlaceholder')}
            required
          />
        </div>

        {/* Rule Scope — from API */}
        <div>
          <SearchSelect
            label={t('targetFilter.ruleScope')}
            options={scopeOptions}
            value={safeScope}
            onChange={(_, val) => setRuleScopeId(Number(val))}
            required
          />
        </div>
      </div>

      {/* Rule Description */}
      <div className="w-full">
        <Input
          label={t('targetFilter.description')}
          value={ruleDescription}
          onChange={(e) => setRuleDescription(e.target.value)}
          placeholder={t('targetFilter.descriptionPlaceholder')}
          fullWidth
        />
      </div>
    </div>
  );
}

