'use client';

import { RuleScope } from '@/types/rule-engine.types';
import { Select } from '@/components/common/select';
import { Input } from '@/components/common/Input';
import { useTranslations } from 'next-intl';


interface TargetFilterPanelProps {
  ruleName: string;
  setRuleName: (val: string) => void;
  description: string;
  setDescription: (val: string) => void;
  ruleScopeId: number;
  setRuleScopeId: (val: number) => void;
  ruleCategory: string;
  setRuleCategory: (val: string) => void;
  scopes: RuleScope[];
  corporations: { label: string; value: string }[];
  /** API-driven rule category options from PTIS.RuleCategoryMaster */
  ruleCategoryOptions: { label: string; value: string }[];
}

export default function TargetFilterPanel({
  ruleName, setRuleName,
  ruleScopeId, setRuleScopeId,
  ruleCategory, setRuleCategory,
  description, setDescription,
  scopes, corporations,
  ruleCategoryOptions,
}: TargetFilterPanelProps) {
  const t = useTranslations('ruleEngine');
  const scopeOptions  = scopes.map((s) => ({ label: s.scopeName, value: s.id.toString() }));
  const displayedCorp = corporations[0]?.label ?? '';

  // Ensure the current ruleCategory value exists in the options; default to first item
  const safeCategory =
    ruleCategoryOptions.some((o) => o.value === ruleCategory)
      ? ruleCategory
      : (ruleCategoryOptions[0]?.value ?? '');

  return (
    <div className="flex flex-col gap-5 w-full">
      <div className="grid grid-cols-1 md:grid-cols-5 gap-4 items-end">

        {/* Rule ID — auto-generated by backend */}
        <div>
          <Input label={t('targetFilter.ruleId')} value={t('targetFilter.ruleIdValue')} disabled className="bg-zinc-50 font-semibold" />
        </div>

        {/* Rule Name */}
        <div>
          <Input
            label={t('targetFilter.ruleName')}
            value={ruleName}
            onChange={(e) => setRuleName(e.target.value)}
            placeholder={t('targetFilter.ruleNamePlaceholder')}
            required
          />
        </div>

        {/* Corp — read-only from auth context */}
        <div>
          <Input label={t('targetFilter.corp')} value={displayedCorp} readOnly className="bg-zinc-50 font-bold" />
        </div>

        {/* Rule Category — API-driven select */}
        <div>
          <Select
            label={t('targetFilter.category')}
            options={ruleCategoryOptions}
            value={safeCategory}
            onChange={(_, val) => setRuleCategory(val)}
            required
          />
        </div>

        {/* Rule Scope — from API */}
        <div>
          <Select
            label={t('targetFilter.ruleScope')}
            options={scopeOptions}
            value={ruleScopeId.toString()}
            onChange={(_, val) => setRuleScopeId(Number(val))}
            required
          />
        </div>
      </div>

      <div>
        <Input
          label={t('targetFilter.description')}
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder={t('targetFilter.descriptionPlaceholder')}
          fullWidth
        />
      </div>
    </div>
  );
}

