import type {
  BuildingPermissionData,
  KYCDetailsData,
  OldDetailsData,
  PropertyDetailsData,
  SocialDetails,
  SocietyDetailsData,
} from './ptis-core.types';

export const defaultPropertyDetails: PropertyDetailsData = {
  division: '',
  wardNo: '',
  blockNo: '',
  propertyNo: '',
  partitionNo: '',
  upicId: '',
  taxZoneNo: '',
  subZoneNo: '',
  surveyNo: '',
  plotNo: '',
  propertyDescription: '',
  plotArea: '',
  totalCarpetArea: '',
  builtupArea: '',
  category: '',
  wingNo: '',
  moujaNo: '',
  moujaDescription: '',
};

export const defaultKycDetails: KYCDetailsData = {
  ownerType: '',
  title: '',
  propertyHolderName: '',
  propertyHolderNameMarathi: '',
  occupierName: '',
  occupierNameMarathi: '',
  aadharCardNo: '',
  mobileNumber: '',
  email: '',
  shopName: '',
  address: '',
  wingNo: '',
  flatNo: '',
  shopNo: '',
  buildingName: '',
};

export const defaultSocietyDetails: SocietyDetailsData = {
  buildingSocietyName: '',
  buildingSocietyNameMarathi: '',
  builderName: '',
  builderNameMarathi: '',
  landOwner: '',
  secretaryName: '',
  secretaryNameMarathi: '',
  secretaryMobileNo: '',
  societyEmail: '',
  societyEmailMain: '',
  ocDate: '',
  ocNumber: '',
  societyAddress: '',
  societyAddressMarathi: '',
  managerName: '',
  managerEmail: '',
  managerMobileNo: '',
};

export const defaultBuildingPermission: BuildingPermissionData = {
  completionCertificate: false,
  completionCertificateNumber: '',
  completionCertificateDate: '',
  completionCertificateDoc: '',
  completionCertificateDocData: '',
  completionCertificateDocType: '',
  occupancyCertificate: false,
  occupancyCertificateNumber: '',
  occupancyCertificateDate: '',
  occupancyCertificateDoc: '',
  occupancyCertificateDocData: '',
  occupancyCertificateDocType: '',
  possessionCertificate: false,
  possessionCertificateNumber: '',
  possessionCertificateDate: '',
  possessionCertificateDoc: '',
  possessionCertificateDocData: '',
  possessionCertificateDocType: '',
  index2: false,
  index2Number: '',
  index2Date: '',
  index2Doc: '',
  index2DocData: '',
  index2DocType: '',
  electricBill: false,
  electricBillNumber: '',
  electricBillDate: '',
  electricBillDoc: '',
  electricBillDocData: '',
  electricBillDocType: '',
};

export const defaultOldDetails: OldDetailsData = {
  oldZoneName: '',
  oldWardNo: '',
  oldPropertyNo: '',
  oldPartitionNo: '',
  oldEGovernanceNo: '',
  oldPlotArea: '',
  oldPlotNo: '',
  oldALV: '',
  oldRV: '',
  oldCV: '',
  oldPropertyTax: '',
  oldTotalTax: '',
  oldConstructionYear: '',
  oldCarpetAreaSqMeter: '',
  oldCarpetAreaSqFeet: '',
  oldRegistration: false,
  oldConstructionTypeId: '',
  oldTypeOfUseId: '',
};

export const defaultSocialDetails: SocialDetails = {
  residentialToiletCount: '',
  commercialToiletCount: '',
  liftAvailable: false,
  electricConnection: false,
};
