import { describe, it, expect, vi, beforeEach } from 'vitest';
import { renderHook, act } from '@testing-library/react';
import { useRoomListActions } from '@/hooks/ptis/RoomSubmission/useRoomListActions';
import type { RoomSubmissionState } from '@/hooks/ptis/RoomSubmission/useRoomSubmissionState';
import type { RoomWiseSubmissionProps } from '@/types/room-details.types';
import * as roomSubmissionUtils from '@/lib/utils/RoomSubmission/room-submission.utils';
import * as roomValidation from '@/lib/utils/RoomSubmission/room-validation.utils';
import * as roomCalculation from '@/lib/utils/RoomSubmission/room-calculation.util';

// Mock dependencies
vi.mock('next-intl', () => ({
  useTranslations: vi.fn(() => (key: string) => key),
}));

vi.mock('@/components/common', () => ({
  useConfirm: vi.fn(() => ({
    confirm: vi.fn((options) => {
      if (options.onConfirm) options.onConfirm();
    }),
  })),
}));

vi.mock('react', async () => {
  const actual = await vi.importActual('react');
  return {
    ...actual,
    useTransition: vi.fn(() => [false, (fn: () => void) => fn()]),
  };
});

vi.mock('@/app/[locale]/property-tax/ptis/QuickDataEntry/[propertyId]/FloorSubmission/actions', () => ({
  deleteRoomSubmissionNoRedirectAction: vi.fn(),
  deleteOffsetSubmissionNoRedirectAction: vi.fn(),
}));

describe('useRoomListActions', () => {
  let mockState: RoomSubmissionState;
  let mockProps: RoomWiseSubmissionProps;
  let mockHandleCancelEdit: () => void;

  beforeEach(() => {
    vi.clearAllMocks();

    mockHandleCancelEdit = vi.fn();

    // Create mock state
    mockState = {
      rooms: [
        {
          roomNo: '1',
          length: '0',
          width: '0',
          area: 0,
          roomCount: '1',
          offsetMinus: 'No',
          outer: 'No',
          total: 0,
          remark: '',
          utilities: '',
          shape: '',
          offsets: [],
          isAutoGenerated: false,
          tempId: 'temp-1',
          shapeParams: {},
        },
        {
          roomNo: '2',
          length: '0',
          width: '0',
          area: 0,
          roomCount: '1',
          offsetMinus: 'No',
          outer: 'No',
          total: 0,
          remark: '',
          utilities: '',
          shape: '',
          offsets: [],
          isAutoGenerated: false,
          tempId: 'temp-2',
          shapeParams: {},
        },
      ],
      setRooms: vi.fn(),
      formData: {
        roomNo: '1',
        length: '10',
        width: '10',
        roomCount: '1',
        offsetMinus: 'No',
        outer: 'No',
        remark: 'Bedroom',
        utilities: 'Residential',
        shape: 'Rectangle',
      },
      shapeParameters: {
        length: '10',
        width: '10',
        radius: '',
        base: '',
        height: '',
        side: '',
        base1: '',
        base2: '',
      },
      editingIndex: null,
      currentRoomOffsets: [],
      areaUnit: 'sq.m',
      pendingDeletions: { rooms: [], offsets: [] },
      setPendingDeletions: vi.fn(),
      setValidationErrors: vi.fn(),
    } as unknown as RoomSubmissionState;

    mockProps = {
      isOpen: true,
      onClose: vi.fn(),
      floorNumber: 'G',
      maxRooms: 10,
      availableRooms: 10,
    };
  });

  describe('handleAddRoom', () => {
    it('should add room with valid data', () => {
      // Mock validation to succeed
      vi.spyOn(roomSubmissionUtils, 'calculateRoomArea').mockReturnValue(100);
      vi.spyOn(roomValidation, 'validateRoomDetails').mockReturnValue({
        success: true,
        errors: {},
      });
      vi.spyOn(roomCalculation, 'calculateNetOffsetArea').mockReturnValue(0);
      vi.spyOn(roomCalculation, 'calculateRoomAreas').mockReturnValue({
        mainArea: 100,
        carpetArea: 100,
        builtUpArea: 120,
      });

      const { result } = renderHook(() =>
        useRoomListActions(mockState, mockProps, mockHandleCancelEdit)
      );

      act(() => {
        result.current.handleAddRoom();
      });

      expect(mockState.setRooms).toHaveBeenCalled();
      expect(mockHandleCancelEdit).toHaveBeenCalled();
    });

    it('should reject room when capacity exceeded', () => {
      // Mock validation to fail due to capacity
      vi.spyOn(roomSubmissionUtils, 'calculateRoomArea').mockReturnValue(100);
      vi.spyOn(roomValidation, 'validateRoomDetails').mockReturnValue({
        success: false,
        errors: { roomCount: 'roomSubmission.validation.insufficientEmptySlots' },
      });

      const { result } = renderHook(() =>
        useRoomListActions(mockState, mockProps, mockHandleCancelEdit)
      );

      act(() => {
        result.current.handleAddRoom();
      });

      // Should not add room
      expect(mockState.setRooms).not.toHaveBeenCalled();
      expect(mockHandleCancelEdit).not.toHaveBeenCalled();
    });

    it('should handle edge case: zero area', () => {
      // Mock zero area calculation
      vi.spyOn(roomSubmissionUtils, 'calculateRoomArea').mockReturnValue(0);
      vi.spyOn(roomValidation, 'validateRoomDetails').mockReturnValue({
        success: false,
        errors: { area: 'roomSubmission.validation.selectShapeOrEnterArea' },
      });

      const { result } = renderHook(() =>
        useRoomListActions(mockState, mockProps, mockHandleCancelEdit)
      );

      act(() => {
        result.current.handleAddRoom();
      });

      // Should not add room with zero area
      expect(mockState.setRooms).not.toHaveBeenCalled();
    });

    it('should calculate offset areas correctly', () => {
      const mockOffsets = [
        { area: 10, operation: 'subtract' as const, shapeType: 'Rectangle' },
        { area: 5, operation: 'subtract' as const, shapeType: 'Rectangle' },
      ];

      const stateWithOffsets = {
        ...mockState,
        currentRoomOffsets: mockOffsets,
      } as unknown as RoomSubmissionState;

      vi.spyOn(roomSubmissionUtils, 'calculateRoomArea').mockReturnValue(100);
      vi.spyOn(roomValidation, 'validateRoomDetails').mockReturnValue({
        success: true,
        errors: {},
      });
      vi.spyOn(roomCalculation, 'calculateNetOffsetArea').mockReturnValue(15);
      vi.spyOn(roomCalculation, 'calculateRoomAreas').mockReturnValue({
        mainArea: 100,
        carpetArea: 85, // 100 - 15
        builtUpArea: 102, // 85 * 1.2
      });

      const { result } = renderHook(() =>
        useRoomListActions(stateWithOffsets, mockProps, mockHandleCancelEdit)
      );

      act(() => {
        result.current.handleAddRoom();
      });

      expect(roomCalculation.calculateNetOffsetArea).toHaveBeenCalledWith(mockOffsets);
      expect(mockState.setRooms).toHaveBeenCalled();
    });

    it('should add multiple rooms when roomCount > 1', () => {
      const extendedRooms = [
        ...mockState.rooms,
        {
          roomNo: '3',
          length: '0',
          width: '0',
          area: 0,
          roomCount: '1',
          offsetMinus: 'No',
          outer: 'No',
          total: 0,
          remark: '',
          utilities: '',
          shape: '',
          offsets: [],
          isAutoGenerated: false,
          tempId: 'temp-3',
          shapeParams: {},
        },
      ];

      const stateWithMultipleRooms = {
        ...mockState,
        rooms: extendedRooms,
        formData: {
          ...mockState.formData,
          roomCount: '3',
        },
      } as unknown as RoomSubmissionState;

      vi.spyOn(roomSubmissionUtils, 'calculateRoomArea').mockReturnValue(100);
      vi.spyOn(roomValidation, 'validateRoomDetails').mockReturnValue({
        success: true,
        errors: {},
      });
      vi.spyOn(roomCalculation, 'calculateNetOffsetArea').mockReturnValue(0);
      vi.spyOn(roomCalculation, 'calculateRoomAreas').mockReturnValue({
        mainArea: 100,
        carpetArea: 100,
        builtUpArea: 120,
      });

      const { result } = renderHook(() =>
        useRoomListActions(stateWithMultipleRooms, mockProps, mockHandleCancelEdit)
      );

      act(() => {
        result.current.handleAddRoom();
      });

      expect(mockState.setRooms).toHaveBeenCalled();
    });
  });

  describe('handleUpdateRoom', () => {
    it('should update room with valid data', async () => {
      const stateWithEditingIndex = {
        ...mockState,
        editingIndex: 0,
      } as unknown as RoomSubmissionState;

      vi.spyOn(roomSubmissionUtils, 'calculateRoomArea').mockReturnValue(150);
      vi.spyOn(roomValidation, 'validateRoomDetails').mockReturnValue({
        success: true,
        errors: {},
      });
      vi.spyOn(roomCalculation, 'calculateNetOffsetArea').mockReturnValue(0);
      vi.spyOn(roomCalculation, 'calculateRoomAreas').mockReturnValue({
        mainArea: 150,
        carpetArea: 150,
        builtUpArea: 180,
      });

      const { result } = renderHook(() =>
        useRoomListActions(stateWithEditingIndex, mockProps, mockHandleCancelEdit)
      );

      await act(async () => {
        result.current.handleUpdateRoom();
      });

      expect(mockState.setRooms).toHaveBeenCalled();
      expect(mockHandleCancelEdit).toHaveBeenCalled();
    });

    it('should not update when editingIndex is null', () => {
      const { result } = renderHook(() =>
        useRoomListActions(mockState, mockProps, mockHandleCancelEdit)
      );

      act(() => {
        result.current.handleUpdateRoom();
      });

      expect(mockState.setRooms).not.toHaveBeenCalled();
    });

    it('should handle parallel deletion failures gracefully', async () => {
      const { deleteRoomSubmissionNoRedirectAction, deleteOffsetSubmissionNoRedirectAction } = await import(
        '@/app/[locale]/property-tax/ptis/QuickDataEntry/[propertyId]/FloorSubmission/actions'
      );

      const stateWithPendingDeletions = {
        ...mockState,
        editingIndex: 0,
        pendingDeletions: {
          rooms: [123, 456],
          offsets: [789],
        },
      } as unknown as RoomSubmissionState;

      // Mock some deletions to fail
      vi.mocked(deleteRoomSubmissionNoRedirectAction)
        .mockResolvedValueOnce({ success: true })
        .mockResolvedValueOnce({ success: false, error: 'Failed to delete' });
      
      vi.mocked(deleteOffsetSubmissionNoRedirectAction)
        .mockResolvedValue({ success: false, error: 'Failed to delete offset' });

      vi.spyOn(roomSubmissionUtils, 'calculateRoomArea').mockReturnValue(100);
      vi.spyOn(roomValidation, 'validateRoomDetails').mockReturnValue({
        success: true,
        errors: {},
      });
      vi.spyOn(roomCalculation, 'calculateNetOffsetArea').mockReturnValue(0);
      vi.spyOn(roomCalculation, 'calculateRoomAreas').mockReturnValue({
        mainArea: 100,
        carpetArea: 100,
        builtUpArea: 120,
      });

      const { result } = renderHook(() =>
        useRoomListActions(stateWithPendingDeletions, mockProps, mockHandleCancelEdit)
      );

      await act(async () => {
        await result.current.handleUpdateRoom();
      });

      // Should track failed deletions
      expect(stateWithPendingDeletions.setPendingDeletions).toHaveBeenCalled();
      
      // Should not proceed with update due to deletion failures
      expect(mockState.setRooms).not.toHaveBeenCalled();
    });

    it('should handle deletion errors with proper error message', async () => {
      const stateWithPendingDeletions = {
        ...mockState,
        editingIndex: 0,
        pendingDeletions: {
          rooms: [123],
          offsets: [],
        },
      } as unknown as RoomSubmissionState;

      const { deleteRoomSubmissionNoRedirectAction } = await import(
        '@/app/[locale]/property-tax/ptis/QuickDataEntry/[propertyId]/FloorSubmission/actions'
      );

      // Mock deletion to throw error
      vi.mocked(deleteRoomSubmissionNoRedirectAction).mockRejectedValue(
        new Error('Network error')
      );

      vi.spyOn(roomSubmissionUtils, 'calculateRoomArea').mockReturnValue(100);
      vi.spyOn(roomValidation, 'validateRoomDetails').mockReturnValue({
        success: true,
        errors: {},
      });

      const { result } = renderHook(() =>
        useRoomListActions(stateWithPendingDeletions, mockProps, mockHandleCancelEdit)
      );

      await act(async () => {
        await result.current.handleUpdateRoom();
      });

      // Should not update rooms due to error
      expect(mockState.setRooms).not.toHaveBeenCalled();
    });
  });

  describe('handleDelete', () => {
    it('should delete room with confirmation', async () => {
      const confirmMock = vi.fn((options) => {
        if (options.onConfirm) options.onConfirm();
      });
      
      const { useConfirm } = await import('@/components/common');
      vi.mocked(useConfirm).mockReturnValue({
        confirm: confirmMock,
      });

      const { result } = renderHook(() =>
        useRoomListActions(mockState, mockProps, mockHandleCancelEdit)
      );

      act(() => {
        result.current.handleDelete(0);
      });

      // Confirm was called with delete variant
      expect(confirmMock).toHaveBeenCalled();
      expect(confirmMock.mock.calls[0][0]).toMatchObject({
        variant: 'delete',
      });
    });

    it('should not delete if room does not exist', async () => {
      const confirmMock = vi.fn();
      
      const { useConfirm } = await import('@/components/common');
      vi.mocked(useConfirm).mockReturnValue({
        confirm: confirmMock,
      });

      const { result } = renderHook(() =>
        useRoomListActions(mockState, mockProps, mockHandleCancelEdit)
      );

      act(() => {
        result.current.handleDelete(999); // Invalid index
      });

      // Should return early without calling confirm
      expect(confirmMock).not.toHaveBeenCalled();
    });
  });

  describe('Edge Cases', () => {
    it('should handle negative area values', () => {
      vi.spyOn(roomSubmissionUtils, 'calculateRoomArea').mockReturnValue(-10);
      vi.spyOn(roomValidation, 'validateRoomDetails').mockReturnValue({
        success: false,
        errors: { area: 'Invalid negative area' },
      });

      const { result } = renderHook(() =>
        useRoomListActions(mockState, mockProps, mockHandleCancelEdit)
      );

      act(() => {
        result.current.handleAddRoom();
      });

      expect(mockState.setRooms).not.toHaveBeenCalled();
    });

    it('should handle very large area values', () => {
      vi.spyOn(roomSubmissionUtils, 'calculateRoomArea').mockReturnValue(999999);
      vi.spyOn(roomValidation, 'validateRoomDetails').mockReturnValue({
        success: true,
        errors: {},
      });
      vi.spyOn(roomCalculation, 'calculateNetOffsetArea').mockReturnValue(0);
      vi.spyOn(roomCalculation, 'calculateRoomAreas').mockReturnValue({
        mainArea: 999999,
        carpetArea: 999999,
        builtUpArea: 1199998.8,
      });

      const { result } = renderHook(() =>
        useRoomListActions(mockState, mockProps, mockHandleCancelEdit)
      );

      act(() => {
        result.current.handleAddRoom();
      });

      expect(mockState.setRooms).toHaveBeenCalled();
    });

    it('should handle null/undefined form data gracefully', () => {
      const stateWithNullData = {
        ...mockState,
        formData: {
          roomNo: '',
          length: '',
          width: '',
          roomCount: '',
          offsetMinus: 'No',
          outer: 'No',
          remark: '',
          utilities: '',
          shape: '',
        },
      } as unknown as RoomSubmissionState;

      vi.spyOn(roomSubmissionUtils, 'calculateRoomArea').mockReturnValue(0);
      vi.spyOn(roomValidation, 'validateRoomDetails').mockReturnValue({
        success: false,
        errors: { roomNo: 'roomSubmission.validation.enterRoomNumber' },
      });

      const { result } = renderHook(() =>
        useRoomListActions(stateWithNullData, mockProps, mockHandleCancelEdit)
      );

      act(() => {
        result.current.handleAddRoom();
      });

      expect(mockState.setRooms).not.toHaveBeenCalled();
    });
  });
});
