import { describe, it, expect, vi, beforeEach } from 'vitest';
import { renderHook, act } from '@testing-library/react';
import { useRoomPersistenceActions } from '@/hooks/ptis/RoomSubmission/useRoomPersistenceActions';
import type { RoomSubmissionState } from '@/hooks/ptis/RoomSubmission/useRoomSubmissionState';
import type { RoomWiseSubmissionProps, RoomData } from '@/types/room-details.types';

// Mock dependencies
vi.mock('next-intl', () => ({
  useTranslations: vi.fn(() => (key: string) => key),
}));

vi.mock('@/components/common', () => ({
  useConfirm: vi.fn(() => ({
    confirm: vi.fn((options) => {
      if (options.onConfirm) options.onConfirm();
    }),
  })),
}));

vi.mock('@/lib/utils/RoomSubmission/room-calculation.util', () => ({
  convertAreaUnit: vi.fn((value: number) => value),
}));

vi.mock('@/app/[locale]/property-tax/ptis/QuickDataEntry/[propertyId]/FloorSubmission/actions', () => ({
  deleteRoomSubmissionNoRedirectAction: vi.fn(),
  deleteOffsetSubmissionNoRedirectAction: vi.fn(),
}));

describe('useRoomPersistenceActions', () => {
  let mockState: RoomSubmissionState;
  let mockProps: RoomWiseSubmissionProps;

  beforeEach(() => {
    vi.clearAllMocks();

    const mockRooms: RoomData[] = [
      {
        roomNo: '1',
        length: '10',
        width: '10',
        area: 100,
        roomCount: '1',
        offsetMinus: 'No',
        outer: 'No',
        total: 100,
        carpetArea: 100,
        builtUpArea: 120,
        remark: 'Bedroom',
        utilities: 'Residential',
        shape: 'Rectangle',
        offsets: [],
        isAutoGenerated: false,
        tempId: 'temp-1',
        shapeParams: {},
      },
      {
        roomNo: '2',
        length: '8',
        width: '8',
        area: 64,
        roomCount: '1',
        offsetMinus: 'No',
        outer: 'No',
        total: 64,
        carpetArea: 64,
        builtUpArea: 76.8,
        remark: 'Kitchen',
        utilities: 'Residential',
        shape: 'Rectangle',
        offsets: [],
        isAutoGenerated: false,
        tempId: 'temp-2',
        shapeParams: {},
      },
    ];

    mockState = {
      rooms: mockRooms,
      grandTotal: 164,
      builtupGrandTotal: 196.8,
      areaUnit: 'sq.m',
      setIsUpdating: vi.fn(),
      pendingDeletions: { rooms: [], offsets: [] },
      setPendingDeletions: vi.fn(),
    } as unknown as RoomSubmissionState;

    mockProps = {
      isOpen: true,
      onClose: vi.fn(),
      onUpdate: vi.fn(),
      onRoomsUpdate: vi.fn(),
      onSaveRooms: vi.fn(),
      floorNumber: 'G',
      maxRooms: 10,
      availableRooms: 10,
    };
  });

  describe('handleUpdate', () => {
    it('should successfully update rooms with valid data', async () => {
      const { result } = renderHook(() =>
        useRoomPersistenceActions(mockState, mockProps)
      );

      await act(async () => {
        await result.current.handleUpdate();
      });

      expect(mockState.setIsUpdating).toHaveBeenCalledWith(true);
      expect(mockProps.onRoomsUpdate).toHaveBeenCalledWith(mockState.rooms);
      expect(mockProps.onSaveRooms).toHaveBeenCalled();
      expect(mockProps.onUpdate).toHaveBeenCalledWith(
        expect.objectContaining({
          floorNumber: 'G',
          rooms: mockState.rooms,
          totalAreaSqM: 164,
          builtUpAreaSqM: 196.8,
          roomCount: 2,
        })
      );
      expect(mockState.setIsUpdating).toHaveBeenCalledWith(false);
    });

    it('should reject update when grandTotal is zero', async () => {
      const stateWithZeroTotal = {
        ...mockState,
        grandTotal: 0,
      } as unknown as RoomSubmissionState;

      const { result } = renderHook(() =>
        useRoomPersistenceActions(stateWithZeroTotal, mockProps)
      );

      await act(async () => {
        await result.current.handleUpdate();
      });

      // Should show warning and not proceed
      expect(mockProps.onUpdate).not.toHaveBeenCalled();
      expect(mockState.setIsUpdating).not.toHaveBeenCalled();
    });

    it('should reject update when grandTotal is negative', async () => {
      const stateWithNegativeTotal = {
        ...mockState,
        grandTotal: -50,
      } as unknown as RoomSubmissionState;

      const { result } = renderHook(() =>
        useRoomPersistenceActions(stateWithNegativeTotal, mockProps)
      );

      await act(async () => {
        await result.current.handleUpdate();
      });

      expect(mockProps.onUpdate).not.toHaveBeenCalled();
    });

    it('should execute pending deletions before update', async () => {
      const { deleteRoomSubmissionNoRedirectAction, deleteOffsetSubmissionNoRedirectAction } = await import(
        '@/app/[locale]/property-tax/ptis/QuickDataEntry/[propertyId]/FloorSubmission/actions'
      );

      const stateWithPendingDeletions = {
        ...mockState,
        pendingDeletions: {
          rooms: [123, 456],
          offsets: [789, 101],
        },
      } as unknown as RoomSubmissionState;

      vi.mocked(deleteRoomSubmissionNoRedirectAction).mockResolvedValue({ success: true });
      vi.mocked(deleteOffsetSubmissionNoRedirectAction).mockResolvedValue({ success: true });

      const { result } = renderHook(() =>
        useRoomPersistenceActions(stateWithPendingDeletions, mockProps)
      );

      await act(async () => {
        await result.current.handleUpdate();
      });

      // Should call deletion actions for all pending items
      expect(deleteRoomSubmissionNoRedirectAction).toHaveBeenCalledTimes(2);
      expect(deleteOffsetSubmissionNoRedirectAction).toHaveBeenCalledTimes(2);

      // Should clear pending deletions after successful deletion
      expect(stateWithPendingDeletions.setPendingDeletions).toHaveBeenCalledWith({
        rooms: [],
        offsets: [],
      });

      // Should proceed with update
      expect(mockProps.onUpdate).toHaveBeenCalled();
    });

    it('should handle partial deletion failures', async () => {
      const { deleteRoomSubmissionNoRedirectAction, deleteOffsetSubmissionNoRedirectAction } = await import(
        '@/app/[locale]/property-tax/ptis/QuickDataEntry/[propertyId]/FloorSubmission/actions'
      );

      const stateWithPendingDeletions = {
        ...mockState,
        pendingDeletions: {
          rooms: [123, 456],
          offsets: [789],
        },
      } as unknown as RoomSubmissionState;

      // Mock first room deletion to succeed, second to fail
      vi.mocked(deleteRoomSubmissionNoRedirectAction)
        .mockResolvedValueOnce({ success: true })
        .mockResolvedValueOnce({ success: false, error: 'Delete failed' });

      vi.mocked(deleteOffsetSubmissionNoRedirectAction).mockResolvedValue({ success: true });

      const { result } = renderHook(() =>
        useRoomPersistenceActions(stateWithPendingDeletions, mockProps)
      );

      await act(async () => {
        await result.current.handleUpdate();
      });

      // Should track failed deletions
      expect(stateWithPendingDeletions.setPendingDeletions).toHaveBeenCalledWith({
        rooms: [456], // Only the failed one
        offsets: [],
      });

      // Should NOT proceed with update due to failures
      expect(mockProps.onUpdate).not.toHaveBeenCalled();
      
      // Should reset loading state
      expect(mockState.setIsUpdating).toHaveBeenCalledWith(false);
    });

    it('should handle all deletion failures', async () => {
      const { deleteRoomSubmissionNoRedirectAction } = await import(
        '@/app/[locale]/property-tax/ptis/QuickDataEntry/[propertyId]/FloorSubmission/actions'
      );

      const stateWithPendingDeletions = {
        ...mockState,
        pendingDeletions: {
          rooms: [123],
          offsets: [],
        },
      } as unknown as RoomSubmissionState;

      vi.mocked(deleteRoomSubmissionNoRedirectAction).mockResolvedValue({
        success: false,
        error: 'Server error',
      });

      const { result } = renderHook(() =>
        useRoomPersistenceActions(stateWithPendingDeletions, mockProps)
      );

      await act(async () => {
        await result.current.handleUpdate();
      });

      expect(stateWithPendingDeletions.setPendingDeletions).toHaveBeenCalledWith({
        rooms: [123],
        offsets: [],
      });
      expect(mockProps.onUpdate).not.toHaveBeenCalled();
    });

    it('should handle update errors gracefully', async () => {
      const propsWithErrorCallback = {
        ...mockProps,
        onUpdate: vi.fn(() => {
          throw new Error('Update failed');
        }),
      };

      const { result } = renderHook(() =>
        useRoomPersistenceActions(mockState, propsWithErrorCallback)
      );

      await act(async () => {
        await result.current.handleUpdate();
      });

      // Should reset loading state even on error
      expect(mockState.setIsUpdating).toHaveBeenCalledWith(false);
    });

    it('should convert area units correctly', async () => {
      const { convertAreaUnit } = await import('@/lib/utils/RoomSubmission/room-calculation.util');

      const stateWithSqFt = {
        ...mockState,
        areaUnit: 'sq.ft',
        grandTotal: 1000,
        builtupGrandTotal: 1200,
      } as unknown as RoomSubmissionState;

      const { result } = renderHook(() =>
        useRoomPersistenceActions(stateWithSqFt, mockProps)
      );

      await act(async () => {
        await result.current.handleUpdate();
      });

      // Should convert from sq.ft to sq.m
      expect(convertAreaUnit).toHaveBeenCalledWith(1000, 'sq.ft', 'sq.m');
      expect(convertAreaUnit).toHaveBeenCalledWith(1200, 'sq.ft', 'sq.m');
    });

    it('should count only filled rooms in roomCount', async () => {
      const mixedRooms: RoomData[] = [
        {
          roomNo: '1',
          area: 100,
          total: 100,
          // ... other required fields
        } as RoomData,
        {
          roomNo: '2',
          area: 0, // Empty room
          total: 0,
          // ... other required fields
        } as RoomData,
        {
          roomNo: '3',
          area: 50,
          total: 50,
          // ... other required fields
        } as RoomData,
      ];

      const stateWithMixedRooms = {
        ...mockState,
        rooms: mixedRooms,
        grandTotal: 150,
        builtupGrandTotal: 180,
      } as unknown as RoomSubmissionState;

      const { result } = renderHook(() =>
        useRoomPersistenceActions(stateWithMixedRooms, mockProps)
      );

      await act(async () => {
        await result.current.handleUpdate();
      });

      expect(mockProps.onUpdate).toHaveBeenCalledWith(
        expect.objectContaining({
          roomCount: 2, // Only rooms with area > 0
        })
      );
    });

    it('should call all callback functions when provided', async () => {
      const { result } = renderHook(() =>
        useRoomPersistenceActions(mockState, mockProps)
      );

      await act(async () => {
        await result.current.handleUpdate();
      });

      expect(mockProps.onRoomsUpdate).toHaveBeenCalled();
      expect(mockProps.onSaveRooms).toHaveBeenCalled();
      expect(mockProps.onUpdate).toHaveBeenCalled();
    });

    it('should handle missing optional callbacks', async () => {
      const propsWithoutCallbacks = {
        isOpen: true,
        onClose: vi.fn(),
        floorNumber: 'G',
        maxRooms: 10,
        availableRooms: 10,
      };

      const { result } = renderHook(() =>
        useRoomPersistenceActions(mockState, propsWithoutCallbacks)
      );

      await act(async () => {
        await result.current.handleUpdate();
      });

      // Should not throw error
      expect(mockState.setIsUpdating).toHaveBeenCalledWith(true);
      expect(mockState.setIsUpdating).toHaveBeenCalledWith(false);
    });
  });

  describe('Edge Cases', () => {
    it('should handle very large area values', async () => {
      const stateWithLargeValues = {
        ...mockState,
        grandTotal: 9999999.99,
        builtupGrandTotal: 11999999.99,
      } as unknown as RoomSubmissionState;

      const { result } = renderHook(() =>
        useRoomPersistenceActions(stateWithLargeValues, mockProps)
      );

      await act(async () => {
        await result.current.handleUpdate();
      });

      expect(mockProps.onUpdate).toHaveBeenCalledWith(
        expect.objectContaining({
          totalAreaSqM: 9999999.99,
          builtUpAreaSqM: 11999999.99,
        })
      );
    });

    it('should handle decimal precision correctly', async () => {
      const stateWithDecimals = {
        ...mockState,
        grandTotal: 123.456789,
        builtupGrandTotal: 148.148147,
      } as unknown as RoomSubmissionState;

      const { result } = renderHook(() =>
        useRoomPersistenceActions(stateWithDecimals, mockProps)
      );

      await act(async () => {
        await result.current.handleUpdate();
      });

      expect(mockProps.onUpdate).toHaveBeenCalledWith(
        expect.objectContaining({
          totalAreaSqM: 123.46, // Rounded to 2 decimals
          builtUpAreaSqM: 148.15,
        })
      );
    });

    it('should handle empty rooms array', async () => {
      const stateWithNoRooms = {
        ...mockState,
        rooms: [],
        grandTotal: 0,
      } as unknown as RoomSubmissionState;

      const { result } = renderHook(() =>
        useRoomPersistenceActions(stateWithNoRooms, mockProps)
      );

      await act(async () => {
        await result.current.handleUpdate();
      });

      expect(mockProps.onUpdate).not.toHaveBeenCalled();
    });
  });
});
