export interface FallbackFooterAction {
  actionCommand: string;
  buttonName: string;
  lucideIcon?: string;
  routePath?: string;
  displayOrder: number;
  isEnabled: boolean;
  canView?: boolean;
  canEdit?: boolean;
  canDelete?: boolean;
  haveFullAccess?: boolean;
  haveNoAccess?: boolean;
}

export const FALLBACK_FOOTER_ACTIONS: FallbackFooterAction[] = [
  {
    actionCommand: 'PTIS_QC',
    buttonName: 'QC',
    lucideIcon: 'CheckCircle2',
    routePath: '',
    displayOrder: 60,
    isEnabled: true,
    canView: true,
    canEdit: true,
    canDelete: true,
    haveFullAccess: true,
    haveNoAccess: false,
  },
  {
    actionCommand: 'PTIS_QC_REVERT',
    buttonName: 'QC Revert',
    lucideIcon: 'Undo2',
    routePath: '',
    displayOrder: 70,
    isEnabled: true,
    canView: true,
    canEdit: true,
    canDelete: true,
    haveFullAccess: true,
    haveNoAccess: false,
  },
  {
    actionCommand: 'PTIS_COMBINE',
    buttonName: 'Combine Property',
    lucideIcon: 'Merge',
    routePath: '',
    displayOrder: 80,
    isEnabled: true,
    canView: true,
    canEdit: true,
    canDelete: true,
    haveFullAccess: true,
    haveNoAccess: false,
  },
  {
    actionCommand: 'PTIS_EDIT_ENTRY',
    buttonName: 'Edit Data Entry',
    lucideIcon: 'Pencil',
    routePath: '',
    displayOrder: 135,
    isEnabled: true,
    canView: true,
    canEdit: true,
    canDelete: true,
    haveFullAccess: true,
    haveNoAccess: false,
  },
  {
    actionCommand: 'PTIS_REFRESH',
    buttonName: 'Refresh Taxes',
    lucideIcon: 'RefreshCw',
    routePath: '',
    displayOrder: 140,
    isEnabled: true,
    canView: true,
    canEdit: true,
    canDelete: true,
    haveFullAccess: true,
    haveNoAccess: false,
  },
  {
    actionCommand: 'PTIS_APPLY',
    buttonName: 'Apply Taxes',
    lucideIcon: 'CheckCircle',
    routePath: '',
    displayOrder: 50,
    isEnabled: true,
    canView: true,
    canEdit: true,
    canDelete: true,
    haveFullAccess: true,
    haveNoAccess: false,
  },
  {
    actionCommand: 'PTIS_PARTITION',
    buttonName: 'Society Partition Property',
    lucideIcon: 'Split',
    routePath: '',
    displayOrder: 200,
    isEnabled: true,
    canView: true,
    canEdit: true,
    canDelete: true,
    haveFullAccess: true,
    haveNoAccess: false,
  },
  {
    actionCommand: 'PTIS_TAP_WATER',
    buttonName: 'Water',
    lucideIcon: 'Droplet',
    routePath: '',
    displayOrder: 205,
    isEnabled: true,
    canView: true,
    canEdit: true,
    canDelete: true,
    haveFullAccess: true,
    haveNoAccess: false,
  },
  {
    actionCommand: 'PTIS_ADD',
    buttonName: 'Add',
    lucideIcon: 'Plus',
    routePath: '',
    displayOrder: 210,
    isEnabled: true,
    canView: true,
    canEdit: true,
    canDelete: true,
    haveFullAccess: true,
    haveNoAccess: false,
  },
];
