import {
  BarChart3,
  Building,
  Building2,
  Calculator,
  ClipboardCheck,
  ClipboardList,
  Cog,
  Database,
  FileText,
  Home,
  LayoutDashboard,
  LayoutGrid,
  List,
  Map,
  MapPin,
  Receipt,
  Search,
  Users,
  Wrench,
  Briefcase,
  Settings,
  Shield,
  Layers,
  User,
  Activity,
  Globe,
  FileBarChart,
  Folder,
  HardDrive,
  Box,
  Boxes,
  FileSearch,
  UserCog,
  ShieldCheck,
  ListTree,
  FileSpreadsheet,
  LandPlot,
  Droplet,
  ShoppingCart,
  Trash2,
  Megaphone,
  Timer,
  Landmark,
  Flame,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/** Lucide export names from menu config / getIconNameForScreen — explicit map for tree-shaking */
export const MENU_ICON_MAP: Record<string, LucideIcon> = {
  Home,
  BarChart3,
  Search,
  LayoutDashboard,
  ClipboardCheck,
  ClipboardList,
  FileText,
  Wrench,
  LayoutGrid,
  Map,
  MapPin,
  Database,
  Users,
  Briefcase,
  Settings,
  Shield,
  Layers,
  User,
  Activity,
  Globe,
  FileBarChart,
  Folder,
  HardDrive,
  Box,
  Boxes,
  Building,
  Building2,
  Calculator,
  Cog,
  List,
  Receipt,
  FileSearch,
  UserCog,
  ShieldCheck,
  ListTree,
  FileSpreadsheet,
  LandPlot,
  Droplet,
  ShoppingCart,
  Trash2,
  Megaphone,
  Timer,
  Landmark,
  Flame,
};

/** Map common screen/module names to appropriate icons */
export const NAME_TO_ICON_MAP: Record<string, string> = {
  // Common menu names
  'dashboard': 'LayoutDashboard',
  'home': 'Home',
  'search': 'Search',
  'search property': 'FileSearch',
  'property search': 'FileSearch',
  'ptis': 'Building2',
  'property': 'Building',
  'property tax': 'Building2',
  'masters': 'Database',
  'master': 'Database',
  'report': 'FileBarChart',
  'reports': 'FileBarChart',
  'report engine': 'FileBarChart',
  'gis': 'Map',
  'map': 'Map',
  'user': 'User',
  'users': 'Users',
  'user management': 'UserCog',
  'settings': 'Settings',
  'configuration': 'Cog',
  'configuration settings': 'Cog',
  'office': 'Building',
  'office master': 'Building',
  'ward': 'MapPin',
  'ward master': 'MapPin',
  'tax': 'Receipt',
  'tax zone': 'LandPlot',
  'taxzone': 'LandPlot',
  'assessment': 'ClipboardList',
  'floor': 'Layers',
  'construction': 'Building2',
  'rate': 'Calculator',
  'rate section': 'Calculator',
  'capital value': 'Calculator',
  'rateable value': 'Calculator',
  'admin': 'ShieldCheck',
  'security': 'Shield',
  'role': 'Shield',
  'screen': 'ListTree',
};
