/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState, useCallback, useEffect, useRef } from 'react';
import { calculateRentProgression } from "@/lib/utils/renter-calculations";
import { enrichRenterDetailsFromSession, mapInitialRenterFormData } from "@/lib/utils/renter-form-mapper";
import { mapCustomDateRangesToPostPayload } from "@/lib/utils/renterUtils";
import { toast } from "sonner";
import { RenterFormData, RenterPayload } from "@/types/renter.types";
import { validateRenterForm } from "@/lib/utils/renter-validation";

// Temp ids generated by the UI (Date.now() based) live above this threshold; anything >= is non-persistent.
const TEMP_ID_THRESHOLD = 1_000_000_000_000;

/**
 * Picks the first candidate that is a real, persisted propertyDetailsId.
 * Rejects 0, '', null, undefined, 'new', NaN, and UI temp ids (>= TEMP_ID_THRESHOLD).
 */
const pickValidPropertyDetailsId = (...candidates: unknown[]): number | undefined => {
    for (const c of candidates) {
        if (c === undefined || c === null || c === '' || c === 'new') continue;
        const n = Number(c);
        if (!isNaN(n) && n > 0 && n < TEMP_ID_THRESHOLD) return n;
    }
    return undefined;
};

interface UseRenterFormProps {
    initialData: Record<string, any> | null;
    floorId: string;
    propertyId?: string | number;
    locale?: string;
    saveAction?: (id: string | number, data: any, locale?: string, propertyId?: string | number) => Promise<{ success: boolean; data?: any; error?: any }>;
    onSaveSuccess?: (data: RenterPayload) => void;
}

export const useRenterForm = ({ initialData, floorId, propertyId, locale, saveAction, onSaveSuccess }: UseRenterFormProps) => {
    const [isSaving, setIsSaving] = useState(false);
    const [formData, setFormData] = useState<RenterFormData>(() =>
        mapInitialRenterFormData(initialData, floorId, propertyId)
    );
    const hasHydratedSession = useRef(false);
    const initialDataRef = useRef(initialData);

    // Prefer session-staged data on first client mount; re-map only when server initialData changes.
    useEffect(() => {
        if (!hasHydratedSession.current) {
            hasHydratedSession.current = true;
            const enriched = enrichRenterDetailsFromSession(initialData || {}, floorId);
            setFormData(mapInitialRenterFormData(enriched, floorId, propertyId));
            initialDataRef.current = initialData;
            return;
        }

        if (initialDataRef.current !== initialData) {
            initialDataRef.current = initialData;
            setFormData(mapInitialRenterFormData(initialData, floorId, propertyId));
        }
    }, [initialData, floorId, propertyId]);

    const handleSave = useCallback(async () => {
        if (!formData?.renterDetails) return;

        const { renterDetails } = formData;

        // Enterprise Validation Layer
        const validationErrors = validateRenterForm(renterDetails);
        if (validationErrors.length > 0) {
            validationErrors.forEach(err => toast.error(err.message));
            return;
        }

        setIsSaving(true);
        let didRedirect = false;
        try {
            const calculationResult = calculateRentProgression(renterDetails);
            const renterCustomIncrements = renterDetails.incrementFrequency === "Custom Date"
                ? mapCustomDateRangesToPostPayload(renterDetails.customDateRanges)
                : [];

            const parsedPropertyId = Number(propertyId || formData?.propertyId || formData?.ownerID || 0);
            const finalPropertyId = !isNaN(parsedPropertyId) && parsedPropertyId > 0 ? parsedPropertyId : 1;

            const finalPropertyDetailsId = pickValidPropertyDetailsId(
                floorId,
                formData?.propertyDetailsId,
                formData?.id
            );
            const isUpdate = finalPropertyDetailsId !== undefined;

            const payload: RenterPayload = {
                ...formData,
                propertyId: finalPropertyId,
                ...(isUpdate
                    ? { propertyDetailsId: finalPropertyDetailsId, id: finalPropertyDetailsId }
                    : {}),
                updatedBy: formData?.updatedBy ? Number(formData.updatedBy) : undefined,
                renterYesNo: Boolean(formData?.renterYesNo ?? true),
                renterName: renterDetails.renterName || undefined,
                renterNameEnglish: renterDetails.renterName || undefined,
                rentMonthly: renterDetails.rentAmount ? Number(renterDetails.rentAmount) : undefined,
                rentYearly: renterDetails.rentAmount ? Number(renterDetails.rentAmount) * 12 : undefined,
                agreementFromDate: renterDetails.agreementDateFrom || undefined,
                agreementToDate: renterDetails.agreementDateTo || undefined,
                agreementDate: renterDetails.agreementDate || undefined,
                nonCalculateRentMonthly: renterDetails.selfDeclarationAmount ? Number(renterDetails.selfDeclarationAmount) : (renterDetails.rentAmount ? Number(renterDetails.rentAmount) : 0),
                renterDetails: calculationResult?.renterDetails || [],
                renterMast: calculationResult?.fyBreakdown || [],
                grandTotal: calculationResult?.grandTotal || 0,
                renterCustomIncrements,
                renterTableEntries: calculationResult?.renterTableEntries || [],
            };

            let finalPayload = { ...payload };

            if (saveAction && finalPropertyDetailsId !== undefined) {
                const result = await saveAction(finalPropertyDetailsId, payload, locale, propertyId);
                if (!result?.success) {
                    const errorMsg = typeof result?.error === 'object' && result?.error?.message 
                        ? result.error.message 
                        : (typeof result?.error === 'string' ? result.error : 'Failed to save renter details to server');
                    toast.error(errorMsg);
                    return false;
                }
                if (result?.data) {
                    const savedFloor = result.data as any;
                    const realFloorId = pickValidPropertyDetailsId(
                        savedFloor?.propertyDetailsId,
                        savedFloor?.id,
                        payload.propertyDetailsId,
                        payload.id,
                        floorId
                    ) ?? finalPropertyDetailsId;
                    finalPayload = {
                        ...payload,
                        ...savedFloor,
                        id: realFloorId,
                        propertyDetailsId: realFloorId,
                        rentMonthly: payload.rentMonthly ?? savedFloor?.rentMonthly,
                        nonCalculateRentMonthly: payload.nonCalculateRentMonthly ?? savedFloor?.nonCalculateRentMonthly,
                    };
                }
            }

            const activeFloorId = pickValidPropertyDetailsId(
                finalPayload.id,
                finalPayload.propertyDetailsId,
                floorId
            ) ?? floorId;

            const storageKey = `renter_data_${activeFloorId}`;
            const serializedPayload = JSON.stringify(finalPayload);
            sessionStorage.setItem(storageKey, serializedPayload);

            if (floorId === 'new') {
                sessionStorage.setItem('renter_data_new', serializedPayload);
            }

            try {
                const sessionForm = sessionStorage.getItem('editingFloorForm');
                if (sessionForm) {
                    const parsed = JSON.parse(sessionForm);
                    if (String(parsed.id) === String(activeFloorId) || (activeFloorId === 'new' && (!parsed.id || parsed.id === 'new'))) {
                        const updatedForm = {
                            ...parsed,
                            renter: 'Yes',
                            renterName: (finalPayload as any).renterName || (finalPayload as any).renterNameEnglish || parsed.renterName || '',
                            agreementFromDate: (finalPayload as any).agreementFromDate || parsed.agreementFromDate || null,
                            agreementToDate: (finalPayload as any).agreementToDate || parsed.agreementToDate || null,
                            agreementDate: (finalPayload as any).agreementDate || parsed.agreementDate || null,
                            rentMonthly: (finalPayload as any).rentMonthly || parsed.rentMonthly || 0,
                            rentYearly: (Number((finalPayload as any).rentMonthly) || 0) * 12,
                            renterDetails: (finalPayload as any).renterDetails || parsed.renterDetails || [],
                            renterMast: (finalPayload as any).renterMast || parsed.renterMast || [],
                        };
                        sessionStorage.setItem('editingFloorForm', JSON.stringify(updatedForm));
                    }
                }
            } catch {
                // Session sync is best-effort; save already succeeded.
            }

            if (onSaveSuccess) {
                onSaveSuccess(finalPayload);
                didRedirect = true;
                return true;
            }

            toast.success("Renter details saved");
            return true;
        } catch (_error) {
            toast.error("Failed to process renter data");
            return false;
        } finally {
            if (!didRedirect) {
                setIsSaving(false);
            }
        }
    }, [formData, floorId, saveAction, onSaveSuccess, propertyId, locale]);

    return {
        formData,
        setFormData,
        isSaving,
        handleSave
    };
};
