import { useTranslations } from "next-intl";
import { useConfirm } from "@/components/common";
import { useTransition } from "react";
import { RoomWiseSubmissionProps, FloorData, RoomData } from "@/types/room-details.types";
import { calculateRoomArea } from "@/lib/utils/RoomSubmission/room-submission.utils";
import { validateRoomDetails } from "@/lib/utils/RoomSubmission/room-validation.utils";
import { calculateRoomAreas, calculateNetOffsetArea, convertAreaUnit } from "@/lib/utils/RoomSubmission/room-calculation.util";
import { 
  deleteRoomSubmissionNoRedirectAction, 
  deleteOffsetSubmissionNoRedirectAction 
} from "@/app/[locale]/property-tax/ptis/QuickDataEntry/[propertyId]/FloorSubmission/actions";
import { RoomSubmissionState } from "./useRoomSubmissionState";

export const useRoomListActions = (state: RoomSubmissionState, props: RoomWiseSubmissionProps & { floorData?: FloorData }, handleCancelEdit: () => void) => {
  const t = useTranslations("quickDataEntry");
  const { confirm } = useConfirm();
  const [, startTransition] = useTransition();
  const {
    rooms, setRooms, formData, shapeParameters, editingIndex, currentRoomOffsets,
    areaUnit
  } = state;

  const warning = (msg: string) => {
    confirm({
      variant: "warning",
      title: t("common.warning") || "Warning",
      description: msg,
      confirmText: t("common.ok") || "OK",
      onConfirm: () => { },
    });
  };

  const handleAddRoom = () => {
    const baseArea = calculateRoomArea(formData, shapeParameters);
    const emptySlots: number[] = [];
    rooms.forEach((room, idx) => {
      if ((room.area === 0 && room.total === 0) || idx === editingIndex) emptySlots.push(idx);
    });

    const { success, errors } = validateRoomDetails(
      formData as unknown as Partial<RoomData>,
      emptySlots.length,
      baseArea
    );

    if (!success) {
      const firstErrorKey = Object.values(errors)[0];
      warning(t(firstErrorKey));
      return;
    }

    const roomCount = parseInt(formData.roomCount) || 1;
    const totalOffsetArea = calculateNetOffsetArea(currentRoomOffsets);
    const computed = calculateRoomAreas(baseArea, formData.offsetMinus, totalOffsetArea, formData.outer);

    startTransition(() => {
      setRooms((prev) => {
        const updated = [...prev];
        for (let i = 0; i < roomCount; i++) {
          const slotIdx = emptySlots[i];
          updated[slotIdx] = {
            roomNo: updated[slotIdx].roomNo,
            length: formData.length, width: formData.width, area: baseArea,
            mainArea: baseArea, carpetArea: computed.carpetArea, builtUpArea: computed.builtUpArea,
            roomCount: "1", offsetMinus: formData.offsetMinus, offsets: [...currentRoomOffsets],
            outer: formData.outer,
            total: computed.carpetArea,
            areaSqMtr: baseArea,
            totalAreaSqMtr: computed.carpetArea,
            remark: formData.remark === "-Select-" ? "" : formData.remark,
            utilities: formData.utilities === "-Select-" ? "" : formData.utilities,
            roomType: formData.utilities === "-Select-" ? "" : formData.utilities,
            shape: formData.shape === "-Select-" ? "" : formData.shape,
            shapeParams: { ...shapeParameters },
            shapeParameters: { ...shapeParameters },
            isAutoGenerated: false, isAutoFilled: false,
            tempId: updated[slotIdx].tempId || `temp-${Date.now()}-${slotIdx}`
          };
        }
        return updated;
      });
      handleCancelEdit();
    });
  };

  const handleUpdateRoom = () => {
    if (editingIndex === null) return;
    const baseArea = calculateRoomArea(formData, shapeParameters);
    
    const emptySlots: number[] = [];
    rooms.forEach((room, idx) => { 
      if (room.area === 0 && room.total === 0 && idx !== editingIndex) emptySlots.push(idx); 
    });

    const { success, errors } = validateRoomDetails(
      formData as unknown as Partial<RoomData>,
      emptySlots.length + 1, // Include current room being edited
      baseArea
    );

    if (!success) {
      const firstErrorKey = Object.values(errors)[0];
      warning(t(firstErrorKey));
      return;
    }

    const roomCount = parseInt(formData.roomCount) || 1;
    const additionalRoomsNeeded = roomCount - 1;

    const computed = calculateRoomAreas(baseArea, formData.offsetMinus, calculateNetOffsetArea(currentRoomOffsets), formData.outer);
    const currentRoom = rooms[editingIndex];

    startTransition(async () => {
      const { pendingDeletions, setPendingDeletions } = state;
      
      try {
        const roomResults = await Promise.all(
          pendingDeletions.rooms.map(async (roomId) => ({
            id: roomId,
            success: (await deleteRoomSubmissionNoRedirectAction(roomId))?.success
          }))
        );
        
        const offsetResults = await Promise.all(
          pendingDeletions.offsets.map(async (offsetId) => ({
            id: offsetId,
            success: (await deleteOffsetSubmissionNoRedirectAction(offsetId))?.success
          }))
        );

        const failedRooms = roomResults.filter(r => !r.success).map(r => r.id);
        const failedOffsets = offsetResults.filter(o => !o.success).map(o => o.id);

        setPendingDeletions({ rooms: failedRooms, offsets: failedOffsets });
        if (failedRooms.length > 0 || failedOffsets.length > 0) {
          warning(t("roomSubmission.validation.someDeletionsFailed") || "Some deletions failed. Please try again.");
          return;
        }
      } catch (err) {
        const errorMsg = err instanceof Error 
          ? err.message 
          : t("roomSubmission.validation.failedPendingDeletions") || "Failed to execute pending deletions. Please try again.";
        warning(errorMsg);
        return;
      }

      // ...existing code...
      setRooms((prev) => {
        const updated = [...prev];
        // Only update roomNo if not set, otherwise preserve user-entered roomNo
        updated[editingIndex] = {
          ...currentRoom,
          roomNo: formData.roomNo || currentRoom.roomNo,
          length: formData.length, width: formData.width, area: baseArea, mainArea: baseArea,
          carpetArea: computed.carpetArea, builtUpArea: computed.builtUpArea, roomCount: "1",
          offsetMinus: formData.offsetMinus, offsets: [...currentRoomOffsets], roomWiseMinusData: [...currentRoomOffsets],
          outer: formData.outer,
          total: computed.carpetArea,
          areaSqMtr: baseArea,
          totalAreaSqMtr: computed.carpetArea,
          remark: formData.remark === "-Select-" ? "" : formData.remark,
          utilities: formData.utilities === "-Select-" ? "" : formData.utilities,
          roomType: formData.utilities === "-Select-" ? "" : formData.utilities,
          shape: formData.shape === "-Select-" ? "" : formData.shape,
          shapeParams: { ...shapeParameters },
          shapeParameters: { ...shapeParameters },
          isAutoFilled: false
        };

        if (additionalRoomsNeeded > 0) {
          const followingEmptySlots = [];
          for (let i = editingIndex + 1; i < updated.length; i++) {
            if (updated[i].area === 0 && updated[i].total === 0) followingEmptySlots.push(i);
          }
          const roomsToFill = Math.min(additionalRoomsNeeded, followingEmptySlots.length);
          for (let i = 0; i < roomsToFill; i++) {
            const slotIdx = followingEmptySlots[i];
            updated[slotIdx] = {
              ...updated[editingIndex],
              id: updated[slotIdx].id,
              tempId: updated[slotIdx].tempId,
              isAutoGenerated: false,
              isAutoFilled: true,
              roomNo: updated[slotIdx].roomNo // preserve existing roomNo for empty slots
            };
          }
        }
        return updated;
      });
      handleCancelEdit();
    });
  };

  const handleDelete = (index: number) => {
    const roomToDelete = rooms[index];
    if (!roomToDelete) return;
    const roomDbId = roomToDelete.id || roomToDelete.roomWiseSubmissionId;
    const hasDbId = roomDbId && Number(roomDbId) > 0 && Number(roomDbId) < 1_000_000_000_000;

    confirm({
      variant: 'delete', title: t('roomSubmission.table.delete'),
      description: t('roomSubmission.validation.deleteConfirm') || 'Are you sure you want to delete this room?',
      confirmText: t('roomSubmission.table.delete'), cancelText: t('roomSubmission.table.cancel'),
      onConfirm: async () => {
        // ...existing code...
        if (hasDbId) {
          state.setPendingDeletions(prev => ({
            ...prev,
            rooms: [...prev.rooms, roomDbId]
          }));
        }

        setRooms((prev) => {
          const updated = prev.filter((_, i) => i !== index);
          const final = updated;
          if (props.onUpdate) {
            const sumTotal = final.reduce((sum, r) => sum + ((r.total || 0) * (parseInt(String(r.roomCount || 1)) || 1)), 0);
            const sumBuiltUp = final.reduce((sum, r) => sum + ((r.builtUpArea || 0) * (parseInt(String(r.roomCount || 1)) || 1)), 0);
            props.onUpdate({
              floorNumber: props.floorNumber || "0", rooms: final,
              totalAreaSqM: parseFloat(convertAreaUnit(sumTotal, areaUnit || "sq.m", "sq.m").toFixed(2)),
              builtUpAreaSqM: parseFloat(convertAreaUnit(sumBuiltUp, areaUnit || "sq.m", "sq.m").toFixed(2)),
              roomCount: final.filter(r => Number(r.area || 0) > 0).length
            });
          }
          return final;
        });
        
        if (editingIndex === index) {
          handleCancelEdit();
        }
      },
    });
  };

  return { handleAddRoom, handleUpdateRoom, handleDelete };
};
