import { RoomFormData } from "@/types/common-details.types";
import { RoomData } from "@/types/room-details.types";
import { INITIAL_SHAPE_PARAMETERS } from "@/components/modules/property-tax/ptis/QuickDataEntry/floorSubmission/RoomSubmission/constants/room-submission.constants";
import { getParameterFields, validateRoomInput } from "@/lib/utils/RoomSubmission/room-submission.utils";
import { RoomSubmissionState } from "./useRoomSubmissionState";

export const useRoomInputActions = (state: RoomSubmissionState, availableRooms: number | null) => {
  const {
    setFormData, formData, setValidationErrors, setShapeParameters,
    setFilledParameters, setSelectedRoomForPlan, currentRoomOffsets,
    setCurrentRoomOffsets, focusRefs
  } = state;

  const handleInputChange = (field: string, value: string) => {
    setFormData((prev: RoomFormData) => {
      const nextFormData = { ...prev, [field]: value };
      const error = validateRoomInput(field, value, nextFormData, availableRooms);
      setValidationErrors((prevErrors) => {
        const newErrors = { ...prevErrors };
        if (error) newErrors[field] = error;
        else delete newErrors[field];
        return newErrors;
      });
      return nextFormData;
    });

    if (field === "outer" && value === "Yes") {
      setFormData((prev: RoomFormData) => ({ ...prev, offsetMinus: "No" }));
      setCurrentRoomOffsets([]);
    }

    if (field === "shape") {
      setShapeParameters(INITIAL_SHAPE_PARAMETERS);
      setFilledParameters([]);
      if (value && value !== "-Select-") {
        const visualizationRoom: RoomData = {
          roomNo: formData.roomNo || "New",
          length: "", width: "", area: 0, roomCount: formData.roomCount || "1",
          offsetMinus: formData.offsetMinus || "No", offsets: currentRoomOffsets,
          outer: formData.outer || "No", total: 0, remark: formData.remark,
          utilities: formData.utilities, shape: value, shapeParams: INITIAL_SHAPE_PARAMETERS,
          isAutoGenerated: false,
        };
        setSelectedRoomForPlan(visualizationRoom);
        setTimeout(() => {
          const params = getParameterFields(value);
          if (params.length > 0) {
            focusRefs.current[`param-${params[0].key}`]?.focus();
          } else {
            focusRefs.current['roomCount']?.focus();
          }
        }, 100);
      } else {
        setSelectedRoomForPlan(null);
      }
    }
  };

  return { handleInputChange };
};
