import { useEffect } from "react";
import { RoomData, RoomWiseSubmissionProps } from "@/types/room-details.types";
import { ShapeParameters } from "@/types/common-details.types";
import { 
  convertAreaUnit, 
  convertDimension 
} from "@/lib/utils/RoomSubmission/room-calculation.util";
import { RoomSubmissionState } from "./useRoomSubmissionState";

export const useRoomInitialization = (state: RoomSubmissionState, props: RoomWiseSubmissionProps, actions: { handleEdit: (idx: number, room?: RoomData) => void }) => {
  const { 
    isOpen, floorNumber, existingRooms, maxRooms 
  } = props;
  const { 
    setMounted, lastInitializedFloorRef, setRooms, 
    rooms, isEditMode, editingIndex, hasAutoActivatedRef,
    setPrevAreaUnit, prevAreaUnit, areaUnit, setShapeParameters, setFormData
  } = state;

  // 1. Mount Status
  useEffect(() => { setMounted(true); }, [setMounted]);

  // 2. Data Initialization & Sync with maxRooms
  useEffect(() => {
    if (!isOpen) {
      lastInitializedFloorRef.current = null;
      return;
    }

    // Always re-initialize if maxRooms changes, floor changes, or database IDs mismatch
    const safeMaxRooms = Math.min(maxRooms || 0, 100);
    const floorChanged = lastInitializedFloorRef.current !== (floorNumber || null);
    const idsMismatch = existingRooms && existingRooms.some((r, i) => {
      const currentRoom = rooms[i];
      if (!currentRoom) return true;
      const apiId = r.roomWiseSubmissionId ?? r.id;
      const stateId = currentRoom.roomWiseSubmissionId ?? currentRoom.id;
      return apiId !== stateId;
    });

    if (rooms.length !== safeMaxRooms || floorChanged || idsMismatch || rooms.length === 0) {
      const initializedRooms = Array.from({ length: safeMaxRooms }, (_, i) => {
        if (existingRooms && existingRooms[i]) {
          const r = existingRooms[i];
          // Merge offsets from all possible sources
          const offsetsRaw = [
            ...(Array.isArray(r.offsets) ? r.offsets : []),
            ...(Array.isArray(r.roomWiseMinusData) ? r.roomWiseMinusData : []),
            ...(Array.isArray(r.minusRooms) ? r.minusRooms : [])
          ];
          // Deduplicate by id/roomWiseMinusId and filter out marked for deletion
          const seen = new Set();
          const offsets = offsetsRaw
            .filter(o => {
              const markedForDeletion = o.MarkedForDeletion ?? o.markedForDeletion;
              return markedForDeletion !== 1 && markedForDeletion !== true;
            })
            .map(o => ({
              ...o,
              id: o.roomWiseMinusId ?? o.id,
              operation: o.isOffset === true ? 'add' : (o.isOffset === false ? 'subtract' : (o.type || o.operation || 'subtract')),
              // Prefer o.area, fallback to o.areaSqMtr, then 0
              area: o.area ?? o.areaSqMtr ?? 0,
              shape: o.shapeType || o.shape || 'Rectangle'
            }))
            .filter(o => {
              const key = o.id || JSON.stringify(o);
              if (seen.has(key)) return false;
              seen.add(key);
              return true;
            });
          return {
            ...r,
            tempId: r.tempId || `init-${Date.now()}-${i}`,
            roomNo: (i + 1).toString(),
            id: r.roomWiseSubmissionId ?? r.id,
            area: Number(r.area || 0),
            total: Number(r.total || 0),
            offsets
          };
        }
        return {
          tempId: `init-${Date.now()}-${i}`,
          roomNo: (i + 1).toString(),
          length: "0", width: "0", area: 0, roomCount: "1", offsetMinus: "No",
          offsets: [], outer: "No", total: 0, remark: "-Select-",
          utilities: "-Select-", shape: "-Select-", isAutoGenerated: true
        };
      });
      setRooms(initializedRooms);
      if (initializedRooms.length > 0) actions.handleEdit(0, initializedRooms[0]);
      lastInitializedFloorRef.current = floorNumber || null;
      return;
    }

    // If already initialized and count matches, do nothing
    lastInitializedFloorRef.current = floorNumber || null;
  }, [isOpen, maxRooms, existingRooms, floorNumber, setRooms, actions, rooms, lastInitializedFloorRef]);

  // 3. Area Unit Conversion Sync
  useEffect(() => {
    if (prevAreaUnit !== areaUnit) {
      const newUnit = areaUnit;
      const targetDimUnit = newUnit === "sq.ft" ? "ft" : "m";
      const oldUnit = newUnit === "sq.ft" ? "sq.m" : "sq.ft";

      setShapeParameters(prev => {
        const next: Partial<ShapeParameters> = {};
        (Object.keys(prev) as Array<keyof ShapeParameters>).forEach(k => {
          const val = prev[k];
          if (typeof val === 'string') next[k] = convertDimension(val, targetDimUnit);
        });
        return next as ShapeParameters;
      });

      setFormData(prev => {
        const isManualArea = !prev.shape || prev.shape === '-Select-';
        return {
          ...prev,
          length: isManualArea 
            ? convertAreaUnit(parseFloat(prev.length || "0"), oldUnit, newUnit).toString()
            : convertDimension(prev.length || "", targetDimUnit),
          width: isManualArea ? (prev.width || "") : convertDimension(prev.width || "", targetDimUnit)
        };
      });

      setRooms(prevRooms => prevRooms.map(room => {
        const isManualArea = !room.shape || room.shape === '-Select-';
        return {
          ...room,
          area: convertAreaUnit(Number(room.area || 0), oldUnit, newUnit),
          total: convertAreaUnit(Number(room.total || 0), oldUnit, newUnit),
          length: isManualArea 
            ? (room.length ? convertAreaUnit(parseFloat(String(room.length)), oldUnit, newUnit).toString() : "")
            : (room.length ? convertDimension(String(room.length), targetDimUnit) : ""),
          width: isManualArea ? (room.width || "") : (room.width ? convertDimension(String(room.width), targetDimUnit) : ""),
          offsets: (room.offsets || []).map(o => ({
            ...o, area: convertAreaUnit(o.area, oldUnit, newUnit),
            length: o.length ? convertDimension(o.length, targetDimUnit) : undefined,
            width: o.width ? convertDimension(o.width, targetDimUnit) : undefined,
          }))
        };
      }));

      setPrevAreaUnit(areaUnit);
    }
  }, [areaUnit, prevAreaUnit, setShapeParameters, setFormData, setRooms, setPrevAreaUnit]);

  // 4. Auto-edit Next Empty Room
  useEffect(() => {
    if (!isOpen || !maxRooms || maxRooms < 2 || isEditMode || editingIndex !== null || rooms.length === 0 || hasAutoActivatedRef.current) return;

    const isRoomFilled = (r: RoomData) => Number(r.area || 0) > 0 && Number(r.total || 0) > 0 && r.remark && r.remark !== "-Select-" && r.shape && r.shape !== "-Select-";
    const lastFilled = [...rooms].reverse().findIndex(isRoomFilled);
    if (lastFilled === -1) return;

    const lastFilledIdx = rooms.length - 1 - lastFilled;
    const nextEmptyIdx = rooms.slice(lastFilledIdx + 1).findIndex(r => !isRoomFilled(r));
    
    if (nextEmptyIdx !== -1) {
      const targetIdx = lastFilledIdx + 1 + nextEmptyIdx;
      hasAutoActivatedRef.current = true;
      setTimeout(() => actions.handleEdit(targetIdx), 200);
    }
  }, [rooms, isOpen, maxRooms, isEditMode, editingIndex, actions, hasAutoActivatedRef]);
};
