import type { PropertyStatVisual } from "@/types/property-search.types";

export const STAT_VISUALS: readonly PropertyStatVisual[] = [
  {
    label: "Register Property",
    i18nKey: "registerProperty",
    iconName: "register-property",
    idleGradient: "from-indigo-100 via-indigo-50 to-white",
    idleBorder: "border-indigo-300",
    idleLabel: "text-indigo-700",
    idleCount: "text-indigo-900",
    iconBg: "bg-indigo-500 shadow-indigo-300/50",
    iconColor: "text-white",
    hoverShadow: "hover:shadow-indigo-300/60",
    activeGradient: "from-indigo-500 via-indigo-600 to-indigo-700",
    activeRing: "ring-indigo-300",
    activeBar: "bg-indigo-200",
  },
  {
    label: "Geo-Sequencing",
    i18nKey: "geoSequencing",
    iconName: "geo-sequencing",
    idleGradient: "from-cyan-100 via-cyan-50 to-white",
    idleBorder: "border-cyan-300",
    idleLabel: "text-cyan-700",
    idleCount: "text-cyan-900",
    iconBg: "bg-cyan-500 shadow-cyan-300/50",
    iconColor: "text-white",
    hoverShadow: "hover:shadow-cyan-300/60",
    activeGradient: "from-cyan-500 via-cyan-600 to-cyan-700",
    activeRing: "ring-cyan-300",
    activeBar: "bg-cyan-200",
  },
  {
    label: "Survey",
    i18nKey: "survey",
    iconName: "survey",
    idleGradient: "from-orange-100 via-orange-50 to-white",
    idleBorder: "border-orange-300",
    idleLabel: "text-orange-700",
    idleCount: "text-orange-900",
    iconBg: "bg-orange-500 shadow-orange-300/50",
    iconColor: "text-white",
    hoverShadow: "hover:shadow-orange-300/60",
    activeGradient: "from-orange-500 via-orange-600 to-orange-700",
    activeRing: "ring-orange-300",
    activeBar: "bg-orange-200",
  },
  {
    label: "Data Processing",
    i18nKey: "dataProcessing",
    iconName: "data-processing",
    idleGradient: "from-teal-100 via-teal-50 to-white",
    idleBorder: "border-teal-300",
    idleLabel: "text-teal-700",
    idleCount: "text-teal-900",
    iconBg: "bg-teal-500 shadow-teal-300/50",
    iconColor: "text-white",
    hoverShadow: "hover:shadow-teal-300/60",
    activeGradient: "from-teal-500 via-teal-600 to-teal-700",
    activeRing: "ring-teal-300",
    activeBar: "bg-teal-200",
  },
  {
    label: "Quality Analysis",
    i18nKey: "qualityAnalysis",
    iconName: "quality-analysis",
    idleGradient: "from-emerald-100 via-emerald-50 to-white",
    idleBorder: "border-emerald-300",
    idleLabel: "text-emerald-700",
    idleCount: "text-emerald-900",
    iconBg: "bg-emerald-500 shadow-emerald-300/50",
    iconColor: "text-white",
    hoverShadow: "hover:shadow-emerald-300/60",
    activeGradient: "from-emerald-500 via-emerald-600 to-emerald-700",
    activeRing: "ring-emerald-300",
    activeBar: "bg-emerald-200",
  },
  {
    label: "Assessment Completed",
    i18nKey: "assessmentCompleted",
    iconName: "assessment-completed",
    idleGradient: "from-violet-100 via-violet-50 to-white",
    idleBorder: "border-violet-300",
    idleLabel: "text-violet-700",
    idleCount: "text-violet-900",
    iconBg: "bg-violet-500 shadow-violet-300/50",
    iconColor: "text-white",
    hoverShadow: "hover:shadow-violet-300/60",
    activeGradient: "from-violet-500 via-violet-600 to-violet-700",
    activeRing: "ring-violet-300",
    activeBar: "bg-violet-200",
  },
];
